# Generated by Django 4.1.7 on 2023-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regBody', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('decisionType', models.CharField(max_length=100)),
                ('allegationType', models.CharField(max_length=100)),
            ],
        ),
    ]
